-- Bobby Office article comments.
-- Run this in Supabase SQL Editor after the user system SQL.

create or replace function public.is_bobby_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(auth.jwt() ->> 'email', '') in (
    'h981411799@126.com',
    'gg981411799@126.com'
  );
$$;

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  post_slug text not null,
  user_id uuid default auth.uid() references auth.users(id) on delete cascade,
  message text not null check (char_length(trim(message)) between 1 and 1000),
  approved boolean default false,
  review_status text not null default 'pending',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.comments
  alter column approved set default false;

alter table public.comments
  alter column review_status set default 'pending';

update public.comments
set review_status = case
  when approved = true then 'approved'
  when review_status = 'hidden' then 'hidden'
  else 'pending'
end;

alter table public.comments
  drop constraint if exists comments_review_status_check;

alter table public.comments
  add constraint comments_review_status_check
  check (review_status in ('pending', 'approved', 'hidden'));

create or replace function public.set_comments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_comments_updated_at on public.comments;
create trigger set_comments_updated_at
before update on public.comments
for each row execute function public.set_comments_updated_at();

alter table public.comments enable row level security;

drop policy if exists "comments_insert_own" on public.comments;
create policy "comments_insert_own"
on public.comments
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "comments_select_visible" on public.comments;
create policy "comments_select_visible"
on public.comments
for select
to anon, authenticated
using (
  approved = true
  or public.is_bobby_admin()
);

drop policy if exists "comments_delete_own" on public.comments;
create policy "comments_delete_own"
on public.comments
for delete
to authenticated
using (user_id = auth.uid() or public.is_bobby_admin());

create or replace function public.article_comments(
  target_post_slug text,
  page_number integer default 1,
  page_size integer default 10
)
returns table (
  id bigint,
  post_slug text,
  user_id uuid,
  message text,
  approved boolean,
  review_status text,
  created_at timestamptz,
  nickname text,
  avatar_url text,
  total_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  with visible_comments as (
    select
      c.id,
      c.post_slug,
      c.user_id,
      c.message,
      coalesce(c.approved, true) as approved,
      c.review_status,
      c.created_at,
      p.nickname,
      p.avatar_url
    from public.comments c
    left join public.profiles p on p.id = c.user_id
    where c.post_slug = target_post_slug
      and (
        coalesce(c.approved, false) = true
        or public.is_bobby_admin()
      )
  )
  select
    visible_comments.*,
    count(*) over () as total_count
  from visible_comments
  order by created_at desc nulls last, id desc
  limit greatest(page_size, 1)
  offset greatest(page_number - 1, 0) * greatest(page_size, 1);
$$;

create or replace function public.set_article_comment_approved(
  comment_id bigint,
  next_approved boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_bobby_admin() then
    raise exception '猫老板不允许进入这里';
  end if;

  update public.comments
  set approved = next_approved,
      review_status = case when next_approved then 'approved' else 'hidden' end,
      updated_at = now()
  where id = comment_id;
end;
$$;

create or replace function public.delete_article_comment(comment_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.comments c
    where c.id = comment_id
      and (c.user_id = auth.uid() or public.is_bobby_admin())
  ) then
    raise exception '猫老板不允许删除这条评论';
  end if;

  delete from public.comments
  where id = comment_id;
end;
$$;

grant select, insert, delete on public.comments to anon, authenticated;
grant execute on function public.article_comments(text, integer, integer) to anon, authenticated;
grant execute on function public.set_article_comment_approved(bigint, boolean) to authenticated;
grant execute on function public.delete_article_comment(bigint) to authenticated;
