-- Bobby Office article views and likes.
-- Run this in Supabase SQL Editor before using article view/like widgets.

create table if not exists public.article_views (
  id bigint generated by default as identity primary key,
  post_slug text not null,
  user_id uuid references auth.users(id) on delete set null,
  visitor_id text,
  created_at timestamptz default now()
);

create table if not exists public.article_likes (
  id bigint generated by default as identity primary key,
  post_slug text not null,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at timestamptz default now(),
  constraint article_likes_post_user_unique unique (post_slug, user_id)
);

alter table public.article_views enable row level security;
alter table public.article_likes enable row level security;

drop policy if exists "article_views_read_all" on public.article_views;
create policy "article_views_read_all"
on public.article_views
for select
to anon, authenticated
using (true);

drop policy if exists "article_likes_read_all" on public.article_likes;
create policy "article_likes_read_all"
on public.article_likes
for select
to anon, authenticated
using (true);

drop policy if exists "article_likes_insert_own" on public.article_likes;
create policy "article_likes_insert_own"
on public.article_likes
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "article_likes_delete_own" on public.article_likes;
create policy "article_likes_delete_own"
on public.article_likes
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.increment_article_view(
  target_post_slug text,
  visitor_id text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.article_views (post_slug, user_id, visitor_id)
  values (target_post_slug, auth.uid(), nullif(trim(visitor_id), ''));

  return (
    select count(*)
    from public.article_views
    where post_slug = target_post_slug
  );
end;
$$;

create or replace function public.article_metrics(target_post_slug text)
returns table (
  view_count bigint,
  like_count bigint,
  liked_by_me boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    (select count(*) from public.article_views where post_slug = target_post_slug) as view_count,
    (select count(*) from public.article_likes where post_slug = target_post_slug) as like_count,
    exists (
      select 1
      from public.article_likes
      where post_slug = target_post_slug
        and user_id = auth.uid()
    ) as liked_by_me;
$$;

create or replace function public.toggle_article_like(target_post_slug text)
returns table (
  view_count bigint,
  like_count bigint,
  liked_by_me boolean
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception '请先登录，再给波比档案点赞';
  end if;

  if exists (
    select 1
    from public.article_likes
    where post_slug = target_post_slug
      and user_id = auth.uid()
  ) then
    delete from public.article_likes
    where post_slug = target_post_slug
      and user_id = auth.uid();
  else
    insert into public.article_likes (post_slug, user_id)
    values (target_post_slug, auth.uid());
  end if;

  return query
  select *
  from public.article_metrics(target_post_slug);
end;
$$;

grant select on public.article_views to anon, authenticated;
grant select on public.article_likes to anon, authenticated;
grant execute on function public.increment_article_view(text, text) to anon, authenticated;
grant execute on function public.article_metrics(text) to anon, authenticated;
grant execute on function public.toggle_article_like(text) to authenticated;
