-- Bobby Office user system, profiles, avatars, guestbook, and RLS policies.
-- Run this file in the Supabase SQL Editor.
-- This script is compatible with an existing guestbook_messages table shaped like:
-- id bigint identity primary key, name text not null, approved boolean,
-- user_id uuid default auth.uid(), created_at timestamptz default now(), message text.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.guestbook_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  approved boolean default false,
  user_id uuid default auth.uid(),
  created_at timestamptz default now(),
  message text
);

alter table public.guestbook_messages
  add column if not exists updated_at timestamptz default now();

alter table public.guestbook_messages
  alter column approved set default false;

alter table public.guestbook_messages
  alter column user_id set default auth.uid();

alter table public.guestbook_messages
  alter column created_at set default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'guestbook_messages_user_id_fkey'
      and conrelid = 'public.guestbook_messages'::regclass
  ) then
    alter table public.guestbook_messages
      add constraint guestbook_messages_user_id_fkey
      foreign key (user_id) references auth.users(id) on delete cascade;
  end if;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'guestbook_messages_message_length_check'
      and conrelid = 'public.guestbook_messages'::regclass
  ) then
    alter table public.guestbook_messages
      add constraint guestbook_messages_message_length_check
      check (message is not null and char_length(trim(message)) between 1 and 1000);
  end if;
end;
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_guestbook_messages_updated_at on public.guestbook_messages;
create trigger set_guestbook_messages_updated_at
before update on public.guestbook_messages
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nickname, avatar_url)
  values (
    new.id,
    nullif(trim(coalesce(new.raw_user_meta_data ->> 'nickname', '')), ''),
    null
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop view if exists public.public_guestbook_messages;
create or replace view public.public_guestbook_messages as
select
  m.id,
  m.user_id,
  m.message,
  m.created_at,
  p.nickname,
  p.avatar_url
from public.guestbook_messages m
left join public.profiles p on p.id = m.user_id
where m.approved = true
order by m.created_at desc;

alter table public.profiles enable row level security;
alter table public.guestbook_messages enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "guestbook_insert_own" on public.guestbook_messages;
create policy "guestbook_insert_own"
on public.guestbook_messages
for insert
to authenticated
with check (
  auth.uid() = user_id
  and coalesce(approved, false) = false
  and name = (select p.nickname from public.profiles p where p.id = auth.uid())
);

drop policy if exists "guestbook_select_own" on public.guestbook_messages;
create policy "guestbook_select_own"
on public.guestbook_messages
for select
to authenticated
using (auth.uid() = user_id);

grant usage on schema public to anon, authenticated;
grant select on public.public_guestbook_messages to anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.guestbook_messages to authenticated;

-- Storage policies for the public `avatars` bucket.
-- Users can upload/update/delete only files under their own user id folder.
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists "avatars_public_read" on storage.objects;
create policy "avatars_public_read"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'avatars');

drop policy if exists "avatars_insert_own_folder" on storage.objects;
create policy "avatars_insert_own_folder"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "avatars_update_own_folder" on storage.objects;
create policy "avatars_update_own_folder"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
)
with check (
  bucket_id = 'avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);

drop policy if exists "avatars_delete_own_folder" on storage.objects;
create policy "avatars_delete_own_folder"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'avatars'
  and auth.uid()::text = (storage.foldername(name))[1]
);
