-- Bobby Office feedback center.
-- Run this in Supabase SQL Editor before using /feedback and the admin feedback tab.

create or replace function public.is_bobby_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(auth.jwt() ->> 'email', '') in (
    'h981411799@126.com',
    'gg981411799@126.com'
  );
$$;

create table if not exists public.feedback_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  status text not null default 'pending',
  admin_reply text,
  replied_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.feedback_messages
  alter column user_id set default auth.uid();

alter table public.feedback_messages
  alter column status set default 'pending';

alter table public.feedback_messages
  drop constraint if exists feedback_messages_status_check;

alter table public.feedback_messages
  add constraint feedback_messages_status_check
  check (status in ('pending', 'replied', 'resolved'));

alter table public.feedback_messages
  drop constraint if exists feedback_messages_type_check;

alter table public.feedback_messages
  add constraint feedback_messages_type_check
  check (type in ('suggestion', 'bug', 'praise', 'other'));

alter table public.feedback_messages
  drop constraint if exists feedback_messages_title_length_check;

alter table public.feedback_messages
  add constraint feedback_messages_title_length_check
  check (char_length(trim(title)) between 1 and 120);

alter table public.feedback_messages
  drop constraint if exists feedback_messages_message_length_check;

alter table public.feedback_messages
  add constraint feedback_messages_message_length_check
  check (char_length(trim(message)) between 1 and 2000);

create or replace function public.set_feedback_messages_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_feedback_messages_updated_at on public.feedback_messages;
create trigger set_feedback_messages_updated_at
before update on public.feedback_messages
for each row execute function public.set_feedback_messages_updated_at();

alter table public.feedback_messages enable row level security;

drop policy if exists "feedback_insert_own" on public.feedback_messages;
create policy "feedback_insert_own"
on public.feedback_messages
for insert
to authenticated
with check (
  auth.uid() = user_id
  and status = 'pending'
  and admin_reply is null
  and replied_at is null
);

drop policy if exists "feedback_select_own_or_admin" on public.feedback_messages;
create policy "feedback_select_own_or_admin"
on public.feedback_messages
for select
to authenticated
using (auth.uid() = user_id or public.is_bobby_admin());

drop policy if exists "feedback_update_admin" on public.feedback_messages;
create policy "feedback_update_admin"
on public.feedback_messages
for update
to authenticated
using (public.is_bobby_admin())
with check (public.is_bobby_admin());

drop policy if exists "feedback_delete_admin" on public.feedback_messages;
create policy "feedback_delete_admin"
on public.feedback_messages
for delete
to authenticated
using (public.is_bobby_admin());

create or replace function public.admin_feedback_messages()
returns table (
  id bigint,
  user_id uuid,
  email text,
  type text,
  title text,
  message text,
  status text,
  admin_reply text,
  replied_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz,
  nickname text,
  avatar_url text
)
language sql
stable
security definer
set search_path = public, auth
as $$
  select
    f.id,
    f.user_id,
    u.email::text,
    f.type,
    f.title,
    f.message,
    f.status,
    f.admin_reply,
    f.replied_at,
    f.created_at,
    f.updated_at,
    p.nickname,
    p.avatar_url
  from public.feedback_messages f
  left join public.profiles p on p.id = f.user_id
  left join auth.users u on u.id = f.user_id
  where public.is_bobby_admin()
  order by f.created_at desc nulls last, f.id desc;
$$;

create or replace function public.admin_reply_feedback(
  feedback_id bigint,
  reply_text text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_bobby_admin() then
    raise exception '猫老板不允许进入这里';
  end if;

  update public.feedback_messages
  set admin_reply = nullif(trim(reply_text), ''),
      status = 'replied',
      replied_at = now(),
      updated_at = now()
  where id = feedback_id;
end;
$$;

create or replace function public.admin_set_feedback_status(
  feedback_id bigint,
  next_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_bobby_admin() then
    raise exception '猫老板不允许进入这里';
  end if;

  if next_status not in ('pending', 'replied', 'resolved') then
    raise exception 'Invalid feedback status';
  end if;

  update public.feedback_messages
  set status = next_status,
      updated_at = now()
  where id = feedback_id;
end;
$$;

create or replace function public.admin_delete_feedback(feedback_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_bobby_admin() then
    raise exception '猫老板不允许进入这里';
  end if;

  delete from public.feedback_messages
  where id = feedback_id;
end;
$$;

grant select, insert on public.feedback_messages to authenticated;
grant execute on function public.admin_feedback_messages() to authenticated;
grant execute on function public.admin_reply_feedback(bigint, text) to authenticated;
grant execute on function public.admin_set_feedback_status(bigint, text) to authenticated;
grant execute on function public.admin_delete_feedback(bigint) to authenticated;
